### ISSUE TITLE
Use Schematica in project to assist in planning

### ISSUE THREAD

**Issue by riking** [AngleWyrm/Colonies#101]
MCF thread: www.minecraftforum.net/topic/1468779-147-schematica/
According to https://gist.github.com/Lunatrius/2e44a506387d970d33f3, this project is interested in using Lunatrius' mod.
This is wholly possible and reasonable.

Schematica and its source is released under the [CreativeCommons Attribution-NonCommercial-ShareAlike 3.0 Unported (CC BY-NC-SA 3.0) license](http://creativecommons.org/licenses/by-nc-sa/3.0/). Click the link for information about the license.

This means that you can use it, as long as you
- [ ] Credit Lunatrius with creation of that part
- [ ] Do not sell the mod for money
- [ ] The whole project must be released under a similar license

Or ask him/her for permission to use it without the commercial/sharealike portions.

Anyway, the point of this was to point out that sending that message was pointless unless you wanted exemptions from those portions of the license.

**Comment by riking** [comment]
By the way, if I found the wrong project, feel free to humiliate me

**Comment by AngleWyrm** [comment]
See issue #82, building schematics.
