### ISSUE TITLE
All chests in game have the same texture.

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#11]
This might be a hard-coded constant in the render routine

**Comment by AngleWyrm** [comment]
If it turns out to be too much to fix this, then we will just come up with some other solution instead of chests. I'm wondering if basic blocks, like they used in MineColony might be easier to deal with.

This would mean the loss of some of about a week's code from three coders. But it would mean that we don't have to spend yet another week trying to extract the chest merging functions.

And working on this project should be fun. What do you think?

**Comment by vector67** [comment]
Oh, that's easy, to extract the chest merging function, I've gotten pretty
familiar with the code, I know where things are.
Thanks
Jeffrey

**Comment by Jackerty** [comment]
Fix is to call super.renderChest() method at ColoniesChestRenderHelper's renderChest() method and also make put if that looks if blocks Id is the same as ColoniesChest's id.
