### ISSUE TITLE
Server side not working yet

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#22]
server code crashes with a file not found on minecraft.net.SoundManager

**Comment by CliffracerX** [comment]
Are you using a SoundManager that adds the sounds to your mod?

If so, add a SideOnly(Side.CLIENT) to the function that registers sounds.  E.g:
@SideOnly(Side.CLIENT)
public void methodName()
{
//Adds sounds here
}

This should fix it, as then the method that registers the new sounds won't be called serverside, and should fix the problem.  I hope this helped!
