### ISSUE TITLE
Chest placement can crash the game

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#27]
From stabtokill at http://mcmresurrection.enjin.com/forum/post/last/m/9402108/viewthread/5153927-openalpha-3severechest-next-to-each-other#last

![4tac76.png](https://f.cloud.github.com/assets/2841453/3562/55016350-42d4-11e2-8e4e-44f7c40557d8.png)
In the picture the color chest is the colonies chest and the normal ones are the normal ones.

If you put another Colonies chest in the corner, it crashes the game and the world can not be played again (world lost)

**Comment by Josh-Larson** [comment]
The mistake was a casting error. It needs to check the instanceof the chest before it casts it.
