### ISSUE TITLE
GUI and Hotbar chests appear as ordinary chests

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#33]
It would be better if the chests drawn in the GUI and on the user's hotbar were pictures of the final chest as drawn in-world, instead of the default chest.

**Comment by stabtokill** [comment]
do we have a items AND block  .png?
maybe that is the problem?

EX:
public class CommonProxy {
        public static String ITEMS_PNG = "/tutorial/generic/items.png";
        public static String BLOCK_PNG = "/tutorial/generic/block.png";

**Comment by AngleWyrm** [comment]
Changed code references to label the two primary texture files as BLOCK_PNG and ITEMS_PNG for clarity

**Comment by stabtokill** [comment]
this is the block PNG
EX in code:
public static String BLACKSMITHCHEST_PNG = "/colonies/pmardle/gfx/Blacksmithchest.png";

now should there be a PNG of the item?

**Comment by stabtokill** [comment]
For an Item
public String getTextureFile () {
        return CommonProxy.ITEMS_PNG;
}
For a Block
public String getTextureFile () {
        return CommonProxy.BLOCK_PNG;
}

**Comment by AngleWyrm** [comment]
A chest is not a block and is also not an item, as far as texturing is concerned.
They don't use those files, nor could they.

Have a look at the graphics contained in any of pmardle/gfx/*chest.png
Then compare that to the graphic you see when you open the files refered to by ITEMS_PNG and BLOCK_PNG

**Comment by AngleWyrm** [comment]
Narrowed it down to ColoniesChestRenderHelper.renderChest()

**Comment by vector67** [comment]
Refer to bug #88

**Comment by AngleWyrm** [comment]
This Issue, #33, about the appearance of chests in GUI & hotbar  is closed.
There is a separate issue, #88, about chest behavior which is open.
