### ISSUE TITLE
Default chest can be seen and built when in Creative mode

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#36]
there's a problem with the render function depending on a global instance of the default chest.

**Comment by AngleWyrm** [comment]
This is related to #33

**Comment by stabtokill** [comment]
can you do this?...

In BlockColoniesChest.class, take out this:

setCreativeTab(CreativeTabs.tabDecorations);

And then put it in each block class, like (in BlockTownHall.class) EX:

```
public BlockTownHall(int id) {
    super(id);
    setBlockName("block.townhall");
    setCreativeTab(CreativeTabs.tabDecorations);
}
```

**Comment by AngleWyrm** [comment]
Yes, good solution
