### ISSUE TITLE
Citizens don't despawn

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#39]
From QuickHead555 at http://mcmresurrection.enjin.com/forum/m/9402108/viewthread/5206803

"So yeah, when it was night time, the Citizens spawned.."

**Comment by AngleWyrm** [comment]
You can see pigs and cows at night as well, doesn't mean they spawned at night.
It is likely the citizens seen spawned during the day, and haven't despawned.

Simply making citizens de-spawn might not be a good idea. Will the player lose valuable citizens if they get separated?

**Comment by AngleWyrm** [comment]
Might be able to go with something like the wolves, which do

protected boolean canDespawn(){
    return !isWolfTamed();
}

But there's still what if the player breaks down their town hall to move it; do all citizens outside the loaded chunks evaporate?

**Comment by stabtokill** [comment]
don't have then de-spawn at all?

when they spawn they should go through checks.
checks are:
- town hall is placed?
- town has room for new citizen?(open house available?)

**Comment by AngleWyrm** [comment]
The town hall does spawning from it's updateEntity function, which will take care of both timing and population cap. Individual citizens double-check that they have a homeTown and a home as part of a search-for-home AI task.
