### ISSUE TITLE
Missing Version

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#4]
So i've been working on the code for a while, and now suddenly it crashes. the error message is
2012-11-26 08:24:15

Warning:

[ForgeModLoader] Mod Colonies is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version r1
2012-11-26 08:24:26 [INFO] [STDERR] java.lang.IllegalArgumentException: duplicate key: Colonies

This doesn't seem to be a problem with any of my code. it seems to be a problem with the versioning/info file.

**Comment by vector67** [comment]
Info, it seems that it only happens when I import pmardles code

**Comment by vector67** [comment]
Ok, just figured out the problem. The ironchests code sets up the mod, and Anglewyrms code also sets up the mod. So when both of them are used, we get conflicts, Hence the problem "duplicate key"

**Comment by AngleWyrm** [comment]
Yeah, the iron chests code is in a separate branch (ColonyChest) because it causes conflicts. Also, the iron chests code is not a simple chest with a few modifications, it's a rather extensive project.
