### ISSUE TITLE
Double-chest placement

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#42]
It looks as if chests are being placed twice. When setting down a  place of business, or home, the chat box message happens twice.

I think this is responsible for Issue #41, where a phantom town hall was continuously spawning ghost citizens.

It is probably also responsible for issue #43, where the population of town halls doesn't seem to work properly., and is probably being displayed from the phantom town hall.

Currently suspect an extra instance of TileEntityColoniesChest is being created.

**Comment by stabtokill** [comment]
![2012-12-25_12 50 54](https://f.cloud.github.com/assets/2895786/30586/9fec3a6a-4ec4-11e2-9001-5c50aa02e699.png)

This may help:
 but if you place down a townhall, then place down another townhall a few blocks away(NOT next to each other)
then destroy it( in the end, the first townhall is the only one still there).

The first chest then becomes "nothing" I can not place down a house, even though there is a townhall place (look in picture)

-Any questions?
