### ISSUE TITLE
Citizen texture behavior when struck

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#52]
From UndeadMonkey at http://mcmresurrection.enjin.com/forum/post/last/m/9402108/viewthread/5325973-texturegraphic-bug#last

"I noticed when hitting a Colony's citizen, that the texture of the sides of their heads turn white for a brief second."

**Comment by stabtokill** [comment]
I was also unable to recreate this "bug"

-I will ask for proof
