### ISSUE TITLE
Townhall chest recipe

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#6]
from pmardle at http://mcmresurrection.enjin.com/forum/m/9402108/viewthread/5057962-prealpha-release-2-feedback

"No recipe to craft TownHall chest?"

**Comment by AngleWyrm** [comment]
Vector67, can you see about getting this in for Pre-Alpha 3? 
If you can, just assgin it to the Pre-Alpha 3 milestone (upper right)
If not, we can work on it next week, and just assign it to the Pre-Alpha 4 milestone

**Comment by AngleWyrm** [comment]
Heh, still getting used to the open/close process, as you can see :)

**Comment by vector67** [comment]
Yup, I should be able to finish this quite easily by Friday

**Comment by AngleWyrm** [comment]
Recipe added.
