### ISSUE TITLE
Additional Chest GUI Buttons

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#8]
from pmardle at http://mcmresurrection.enjin.com/forum/post/last/m/9402108/viewthread/5073128-chest-guis#last

So I have modified a Chest GUI background to allow space for some GUI buttons to be added.

**Comment by AngleWyrm** [comment]
It's unclear what is desired from this post and this work.

**Comment by vector67** [comment]
He's saying that the He's changed the GUI of the chest, so that we can put buttons at the top for whatever custom functionality we might want

**Comment by AngleWyrm** [comment]
This could be useful for a Rename Town function

**Comment by AngleWyrm** [comment]
chest dimensions aren't normal chest dimensions.
