### ISSUE TITLE
Server not working

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#84]
From pmardle at http://mcmresurrection.enjin.com/forum/post/last/m/9402108/viewthread/5661606-open-0010-critical-crash#last/post/31853349#p31853349

Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.ClassNotFoundException: colonies.anglewyrm.src.ServerProxy
at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:68)

**Comment by vector67** [comment]
Why did you close this, it isn't fixed?

**Comment by AngleWyrm** [comment]
The server-side CTD on startup posted in the crash report for this issue as "ClassNotFoundException: colonies.anglewyrm.src.ServerProxy"  was fixed in Pre-alpha Revision 10c

There's a new issue  #89 for a server crash when placing items. 
There's also a related commit that may resolve that issue.
