### ISSUE TITLE
Town hall population counter stopped working

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#85]
from pmardle at http://mcmresurrection.enjin.com/forum/post/last/m/9402108/viewthread/5662123-open-0010-population#last/post/31854729#p31854729

Townhall always reports 0/0
Message when a person joins says population: 0
When you kill someone it says the correct population..

**Comment by boycat97** [comment]
There is an issue with the playertown variable after saving the first time causes a nullpointerexception. Removing the update so that it doesn't cause anyone a headache while I determine the issue.

**Comment by boycat97** [comment]
I will be on the look out for this to stop working again but it seems to be ok now after a few tweaks.
