### ISSUE TITLE
Plant saplings

### ISSUE THREAD

**Issue by AngleWyrm** [AngleWyrm/Colonies#93]
Lumberjack plants a sapling if he has them in his inventory

**Comment by boycat97** [comment]
Thoughts on this item:
- Maintain a level of saplings, if saplings get below a certain level and the chopping a tree hasn't yielded anything start homeward bound.
- Add sapling inventory based on type of saplings retrieved.
- Maybe if sapling isn't placed after movement look for sapling instead on ground.

**Comment by AngleWyrm** [comment]
- The level of saplings is set in EntityCitizen.desiredInventory (see https://github.com/AngleWyrm/Colonies/blob/master/anglewyrm/src/EntityLumberjack.java, line 25)
- The maintenance of all desiredInventory items is handled by EntityAIMaintainInventoryLevels (see https://github.com/AngleWyrm/Colonies/blob/master/anglewyrm/src/EntityAIMaintainInventoryLevels.java )

For example, the lumberjack currently picks up 2 bread, 5 saplings, 2 stone axes, and 1 iron axe.from his place of employment. (Everyone uses TownHall for this purpose at the moment)
